#!/usr/bin/python
import re
#def reverse_string(s):
#    a = s[::-1]
#def complement(a):

a = 'TGAGTGGCAACCGACGTAACCTATGCAGGTTCTGTCAACTCAACGAATCGCGGTAGCGAGTTTAGAATAGTGGGGGAACAAAACCATCCCCACTTGAATGACTACAACGTGTTGGAAGATGCTACATTCTCTCACGGATCGCTTGTTTCAAAGCCTCCGAACCGTTTCATGACCTCAAGACGAGACTATTGTTGAGCCGGTGAACCGTGCACAATACAGGTAAGTTAGGCCGTGCGCGGGTGCAAATCCGCCTTTCATTTACTTATCCTCACTGTCGCATTGACTGGGGTAGAACATAAACAGATCGTTTGAGCGCTTTGGCGTCTCTTACCGTGGGATTCGTCGTTTACGATGAGACTGTCGGCGGGACCCAGGCCTCCACATGAAAGCAGGGGGGAGTGAGGGGCTTCCGAACCAATACGGGAGTCAATCAGCAATTTTGACTTGTACGTTGTACCTTCTTACAGTTAGCCTCTGGTAATATGGGAGCACTATGCTAACTACAGATACCGGTTCCCTACCTTTCGCTGGGGGATCTTGAGACAACGAACCGTGTATCGGGGTGCCGCCTGTCCAGGGTAGTCTGTGAAATGCCTGTCTCTCCCGCTGCTGTCGCCTTCCGATGGACATTTGGTAGTGGTGACCCGAACCCGCTATCGAGAGTTGTTGAGATCGGCACCATTGAATAGGCTTCTCCTTTCTCCAGAACATATGAATCAGGTATATGGGGGAGATGATACATGGTTTTATATGAGAAGATCCTAGCTAGCGAGTCGGTAATGGGCAGACAGCCCTAGTGCGCATGCGTCGCCCTTACCTAATTGCGGGAAGAACGTGTTCCGCTCAGCTACCCGTATGGTATCGCTACCTCGAACAGATGATGTAGGGTTGTTGCTCGAGGGTTCAACAGTTCGCCCGCACCCCTAAAACCCGGGGTTCAGAGCCCCGATCACCAGCAGTTCGCATTGGATAAACTGGATATAGGCTGCAAGAAAA'
reverse_string = a[::-1]
complement_A_and_T = re.sub('.', lambda m: {'A':'T', 'T':'A'}.get(m.group(), m.group()), reverse_string)
complement_G_and_C = re.sub('.', lambda n: {'C':'G', 'G':'C'}.get(n.group(), n.group()), complement_A_and_T)
print complement_G_and_C
